<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeInvalidRecordsToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required fileName</value>
    <value>[i] field:0:required dir</value>
    <value>[i] recref:1:required invalidRecordList simpleTestPackage.documents.flatfile:invalidRecord</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlmaWxlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZmlsZU5h
bWUiICk7DQpTdHJpbmcJZGlyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3Is
ICJkaXIiICk7DQoNCkZpbGUgZiA9IG5ldyBGaWxlKGRpciwgZmlsZU5hbWUpOw0KQnVmZmVyZWRX
cml0ZXIgb3V0ID0gbnVsbDsNCnRyeSB7DQoJb3V0ID0gbmV3IEJ1ZmZlcmVkV3JpdGVyKG5ldyBG
aWxlV3JpdGVyKGYpKTsNCglJRGF0YVtdCWludmFsaWRSZWNvcmQgPSBJRGF0YVV0aWwuZ2V0SURh
dGFBcnJheSggcGlwZWxpbmVDdXJzb3IsICJpbnZhbGlkUmVjb3JkTGlzdCIgKTsNCglpZiAoIGlu
dmFsaWRSZWNvcmQgIT0gbnVsbCkNCgl7DQoJCWZvciAoIGludCBpID0gMDsgaSA8IGludmFsaWRS
ZWNvcmQubGVuZ3RoOyBpKysgKQ0KCQl7DQoJCQlJRGF0YUN1cnNvciBpbnZhbGlkUmVjb3JkQ3Vy
c29yID0gaW52YWxpZFJlY29yZFtpXS5nZXRDdXJzb3IoKTsNCgkJCVN0cmluZwlwb3NpdGlvbiA9
IElEYXRhVXRpbC5nZXRTdHJpbmcoIGludmFsaWRSZWNvcmRDdXJzb3IsICJwb3NpdGlvbiIgKTsN
CgkJCVN0cmluZwltc2cgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBpbnZhbGlkUmVjb3JkQ3Vyc29y
LCAibXNnIiApOw0KCQkJaW52YWxpZFJlY29yZEN1cnNvci5kZXN0cm95KCk7DQoNCgkJCW91dC53
cml0ZShwb3NpdGlvbiArICIsIiArIG1zZyk7DQoJCQlvdXQubmV3TGluZSgpOw0KCQl9DQoJfQ0K
CQ0KfSBjYXRjaCggSU9FeGNlcHRpb24gaW9lICkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJjb3VsZCBub3Qgd3JpdGUgZmlsZSB0byBwYXRoICIgKyBmaWxlTmFtZSArICI6ICIgKyBp
b2UpOw0KfSBmaW5hbGx5IHsNCglpZiggb3V0ICE9IG51bGwgKSB7DQoJCXRyeSB7DQoJCQlvdXQu
Y2xvc2UoKTsJCQkJCQ0KCQl9IGNhdGNoKCBJT0V4Y2VwdGlvbiBpb2UgKSB7DQoJCQkvLyBpZ25v
cmUNCgkJfQ0KCX0NCn0NCg==</value>
</Values>
