FROM docker.devopsinitiative.com/softwareag/msr:10.3.0.1-sagdevops

ADD --chown=10000:10000 *.zip /opt/softwareag/IntegrationServer/instances/default/replicate/autodeploy/

EXPOSE 5555 9999 8092 8093 8094
